def day = new Date().getDay()
pipeline {
    agent any
    stages {
        stage('Lunes') {
            steps {
              script{
                  if(day==1)
                  println "Lunes"
              }
            }
        }
      stage('Martes') {
            steps {
              script{
                  if(day==2){
                     def dia_completo = new Date()
                    println "Martes"
                    println dia_completo
                  }
                
                }
                
              }
            }
      stage('Miercoles') {
            steps {
              script{
                  if(day==3)
                    println "Miercoles"
              }
            }
        }
      stage('Jueves') {
            steps {
              script{
                  if(day==4)
                   println "Jueves"
              }
            }
        }
      stage('Viernes') {
            steps {
              script{
                  if(day==5){
                      println "Viernes"
                    println("El nombre de usuario que ejecuto la tarea es Iván Sáez Bueno")
                  }
                 
              }
            }
        }
    }
}
